### PR TITLE
[LWR-84] -- Added SearchResults component for the main output of the search page

### PR DESCRIPTION
**Pull request by paboden**
[LWR-84]

Added SearchResults component for the main output of the search page search page. 
Added InlineForm component which is used for the exposed form on the search page.

### CODE REVIEW

**Comment by sleepingmonk** [comment]
I did a quick refactor of the Search Results because I reverted the way sidebar layout works.  And I think I fixed the items per page select field as I don't think it was behaving as you intended.  It should now be vertically centred, in line with the pager.

Please review my changes and also make one more update please. 
https://github.com/JudicialCouncilOfCalifornia/jcc_storybook/pull/41/commits/b15bfb72a7082c78d66bd26b388b51193d67a1aa

The update I'd like you to make is to convert tabs to spaces for the indent in this file.  The Drupal standard is 2 spaces.  I didn't update it myself it would have obscured the diff of my changes I wanted you to review, by changing every line in the file.

Once you confirm my changes match your intention and the tabs are spaces, we can merge this.

Thanks!

**Comment by sleepingmonk** [comment]
Didn't mean to close.  Reopening.

**Comment by paboden** [comment]
@sleepingmonk Not sure how the regular tabs got in there, but fixed it. I checked my settings and its set to the 2 spaces, but I did find my system is also set to auto detect each file for spaced or non-spaced tabs. I must have copied some non spaced snippet into the file from somewhere and that changed the default. This should be good to go

**Comment by sleepingmonk** [comment]
I just started reviewing Baptiste's Publication Results and realized we could probably use a more abstracted "Views List" page that can handle both search.  I think this one is in better shape and we could rename and refactor it a bit.

**Comment by paboden** [comment]
This PR can be closed. It's no longer needed and the SearchResults component has been switched out with ViewResults component in another PR.

**Pull request closed without merging**
